[versions]
tornadofx = "1.7.20"
coroutines-javafx = "1.8.1"
ktor = "2.3.12"
logback = "1.5.6"

[libraries]
tornadofx = { module = "no.tornado:tornadofx", version.ref = "tornadofx" }
coroutines-javafx = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-javafx", version.ref = "coroutines-javafx" }
ktor-client = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
ktor = ["ktor-client", "ktor-cio"]

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.0" }
javafx = { id = "org.openjfx.javafxplugin", version = "0.1.0" }
javamodularity = { id = "org.javamodularity.moduleplugin", version = "1.8.12" }
