[versions]

[libraries]

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.0" }
javafx = { id = "org.openjfx.javafxplugin", version = "0.1.0" }
javamodularity = { id = "org.javamodularity.moduleplugin", version = "1.8.12" }
